spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: ${PORT:8080}